---

- name: ansible playbook to install docker, pull a docker image and run it in amazon linux instance
  hosts: ec2
  become: yes

  vars:
    docker_image_name: moksgo91/emoji:latest

  tasks:
    - name : ping the server  
      action: ping

    - name: wget install
      yum:  
       name: wget
       state: present
       update_cache: true
      become: true

    - name: Install Docker on AWS linux 
      shell: "sudo amazon-linux-extras install docker" 
      become: true

    - name: Start the Docker service 
      shell: "sudo service docker start" 
      become: true

    - name: Start the Docker service 
      shell: "sudo usermod -a -G docker ec2-user" 
      become: true

    - name: set the docker to turn on automatically
      shell: "sudo chkconfig docker on"
      become: true

    - name: pull the latest docker image which was uploaded in the previous step from Dockerhub
      shell: "sudo docker pull {{ docker_image_name }}"
      become: true

    - name: Run the productionized container
      shell: "sudo docker run -d -p 3000:3000 {{ docker_image_name }} --name emoji-search-app"
      become: true

...
